name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job to set up and run tests
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==65.5.0 wheel  # Compatible version
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover  # Modify if using a different test framework

  # Job to deploy the application
  deploy:
    needs: build-and-test  # Only runs if build-and-test job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh
          # Write the private key to a file and set permissions
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the host to known_hosts to prevent interactive prompt
          ssh-keyscan -H 54.145.234.228 >> ~/.ssh/known_hosts
          # Start the SSH agent and add the SSH key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.145.234.228 << 'EOF'
            cd /home/ec2-user/Stock_Proj_1st_OCT
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart stockapp.service
          EOF
